### ISSUE TITLE
Fix searching for undefined title - causes node exception

### ISSUE THREAD

**Issue by samburnstone** [samburnstone/FindThatFilm#9]
Output:

Error: undefined is not a valid uri or options object.
    at request (/Users/samburnstone/Documents/FindThatFilm/Server/node_modules/request/index.js:42:11)
    at Request._callback (/Users/samburnstone/Documents/FindThatFilm/Server/controllers/AmazonVideo.js:38:7)
    at Request.self.callback (/Users/samburnstone/Documents/FindThatFilm/Server/node_modules/request/request.js:373:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/samburnstone/Documents/FindThatFilm/Server/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)

**Comment by samburnstone** [comment]
This seems to have been solved now we verify the films match and only load a page if it exists
